import { Inter } from "next/font/google";
// import "..[locale]/globals.css";

const inter = Inter({ subsets: ["latin"] });
import { useTranslations } from 'next-intl';
import { unstable_setRequestLocale } from 'next-intl/server';
import Navbar from "../components/blog/navbar";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
 
  return (
    <html lang={'en'} data-theme="light">
      <body className={inter.className}>

        <Navbar />
        <main className="min-h-svh max-w-2xl mx-auto py-8 px-4 md:px-0">
          {children}
        </main>
        {/* <Footer n={n} /> */}

      </body>
    </html>
  );
}
