import Article from "@/lib/model/article";
import Navbar from "./components/blog/navbar"
import dbConnect from "@/lib/connect-db";



export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
 

  export default function RootLayout({ children }) {


    return (
      <html data-theme="light" >
        <body>
          {children}
          </body>
      </html>
    )
  }
  