import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import Navbar from "./components/navigation/navbar";
const inter = Inter({ subsets: ["latin"] });
import { useTranslations } from 'next-intl';
import { unstable_setRequestLocale } from 'next-intl/server';
import Footer from "./components/navigation/footer";


// Can be imported from a shared config
const locales =  ['fr', 'en' , 'ar' , 'es' , 'id' , 'it' , 'pt']

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  unstable_setRequestLocale(locale);
  const t = useTranslations('Index');
  const n = useTranslations('navigation')
  const dir = locale === 'ar' ? 'rtl' : 'ltr'
  return (
    <html lang={locale} dir={dir} data-theme="light">
      <body className={inter.className}>

        <Navbar n={n} />
        <main className="min-h-svh max-w-2xl mx-auto py-8 px-4 md:px-0">
          {children}
        </main>
        <Footer n={n} />

      </body>
    </html>
  );
}
