import { Inter } from "next/font/google";
// import "..[locale]/globals.css";

const inter = Inter({ subsets: ["latin"] });

import Article from "@/lib/model/article";
import dbConnect from "@/lib/connect-db";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export async function generateStaticParams() {
    await dbConnect()
    const articles = await Article.find()
    return articles.map((article) => ({ slug : article.slug }));
  }
  
  

export default function RootLayout({ children, params: { locale } }) {
 
  return (
   
        <>
                  {children}

        </>
       
  );
}
